name: Close stale issues and PRs
on:
  schedule:
    - cron: "0 12 1,15 * *"
  workflow_dispatch:

jobs:
  stale:
    if: github.repository == 'XiSenao/docs-islands'
    runs-on: ubuntu-latest
    steps:
      # actions/stale@v10.1.0.
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d
        with:
          days-before-stale: 30
          days-before-close: -1
          stale-issue-label: stale
          stale-pr-label: stale
          # action has a bug that keeps removing the stale label from stale PRs
          # it's thinking that the PR is updated when the stale label is added
          remove-pr-stale-when-updated: false
          operations-per-run: 1000
